setwd("D:/R/rr")
ls()
getwd()
setwd("D:/R/rr/R_Coursera/rprog_data_PA3/")
getwd()
ls()
ls
ls(getwd())
ls(getwd
())
dir()
df <- read.csv("outcome-of-care-measures.csv")
names(df)
df1 <- subset(df, State = "AK", select = c(Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, Hospital.Name))
df1
df1 <- subset(df, min(Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attackselect), select = Hospital.Name)
df1 <- subset(df, min(Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack), select = Hospital.Name)
min(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, na.rm = TRUE)
sapply(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, min, na.rm = TRUE)
mins <- sapply(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, min, na.rm = TRUE)
df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack
mins <- sapply(as.numeric(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack), min, na.rm = TRUE)
mins
mins <- min(as.numeric(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack), na.rm = TRUE)
mins
df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack
mins <- min(as.list(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack), na.rm = TRUE)
mins <- min(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, na.rm = TRUE)
mins <- min(c(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack), na.rm = TRUE)
mins
mins <- min(df$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, na.rm = TRUE)
mins <- min(df$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, na.rm = T)
mins <- min(df$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, na.rm = FALSE)
mins <- min(df[,"Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack"], na.rm = T)
mins <- min(as.numeric(as.character(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack)), na.rm = TRUE)
mins
df1$Hospital.Name[which(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack == 10.1)]
df1[which(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack == 10.1)]
df1[which(df1$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack == 10.1), ]
source("best.R")
best("TX", "heart attack")
source("best.R")
best("TX", "heart attack")
df2 <- df[df[[ "State" ]] == "AK",]
df2
df2 <- df[df[[ "State" ]] == "AK", c("Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack", "Hospital.name")]
df2 <- df[df[[ "State" ]] == "AK", c("Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack", "Hospital.Name")]
df2
source("best.R")
best("TX", "heart attack")
source("best.R")
best("TX", "heart attack")
source("best.R")
best("TX", "heart attack")
source("best.R")
best("TX", "heart attack")
min_val <- min(as.numeric(as.character(df2[["Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack"]])), na.rm = TRUE)
min_val
df2[df2[["Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack"]] == min_val, ]
source("best.R")
best("TX", "heart attack")
ss <- df2[df2[["Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack"]] == min_val, ]
sss <- sort(ss)
sss
source("best.R")
best("AK", "heart attack")
source("best.R")
best("AK", "heart attack")
best("TX", "heart attack")
source("best.R")
best("TX", "heart attack")
best("AK", "heart attack")
source("best.R")
best("TX", "heart attack")
source("best.R")
best("TX", "heart attack")
source("best.R")
best("TX", "heart attack")
a <- 12.0
a
as.numeric(a)
as.double(a)
as.factor(a)
source("best.R")
best("TX", "heart attack")
best("TX", "heart failure")
source("best.R")
best("MD", "heart attack")
best("MD", "pneumonia")
best("DD", "pneumonia")
best("MD", "pneumoniaas")
soucre("rankhospital.R")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
?order
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
source("rankhospital.R")
rankhospital("TX", "heart failure")
rankhospital("TX", "heart failure", 4)
rankhospital("MD", "heart attack", "worst")
rankhospital("MN", "heart attack", 5000)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
rankall("heart attack", 20)
source("rankall.R")
head(rankall("heart attack", 20), 10)
source("rankall.R")
head(rankall("heart attack", 20), 10)
source("rankall.R")
head(rankall("heart attack", 20), 10)
source("rankall.R")
head(rankall("heart attack", 20), 10)
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
# as.data.frame(as.matrix(rank_hospital))
rank_hospital
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
head(rankall("heart attack", "best"), 10)
rankall("heart attack", "best")
c <- rankall("heart attack", "best")
class(c)
source("rankall.R")
c <- rankall("heart attack", "best")
install.packages("rlist")
source("rankall.R")
c <- rankall("heart attack", "best")
c
source("rankall.R")
c <- rankall("heart attack", "best")
c
source("rankall.R")
c <- rankall("heart attack", "best")
source("rankall.R")
c <- rankall("heart attack", "best")
source("rankall.R")
c <- rankall("heart attack", "best")
source("rankall.R")
c <- rankall("heart attack", "best")
c
c <- rankall("heart attack", "best")
source("rankall.R")
c <- rankall("heart attack", "best")
c
source("rankall.R")
c <- rankall("heart attack", "best")
c
source("rankall.R")
c <- rankall("heart attack", "best")
source("rankall.R")
head(rankall("heart attack", 20), 10)
source("rankall.R")
head(rankall("heart attack", 20), 10)
row <- ordered_subdata[which(ordered_subdata[["State"]] == state & ordered_subdata[[outcome_char]] == min_s), c("State", outcome_char, "Hospital.Name")]
source("rankall.R")
head(rankall("heart attack", 20), 10)
source("rankall.R")
head(rankall("heart attack", 20), 10)
source("rankall.R")
head(rankall("heart attack", 20), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("rankall.R")
head(rankall("heart attack", "best"), 10)
source("best.R")
best("SC", "heart attack")
best("NY", "pneumonia")
best("AK", "pneumonia")
rankhospital("NC", "heart attack", "worst")
rankhospital("WA", "heart attack", 7)
rankhospital("TX", "pneumonia", 10)
rankhospital("NY", "heart attack", 7)
source("rankall.R")
r <- rankall("pneumonia", "worst")
r
as.character(subset(r, state == "NJ")$hospital)
source("rankall.R")
r <- rankall("pneumonia", "worst")
r
best("SC", "heart attack")
best("NY", "pneumonia")
best("AK", "pneumonia")
rankhospital("NC", "heart attack", "worst")
rankhospital("WA", "heart attack", 7)
rankhospital("TX", "pneumonia", 10)
rankhospital("NY", "heart attack", 7)
rankhospital("HI", "heart attack", 4)
rankhospital("NJ", "pneumonia", "worst")
rankhospital("NV", "heart failure", 10)
